#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width				0
bspc config window_gap					10
bspc config border_radius				10
bspc config split_ratio					0.53
bspc config single_monocle				true
bspc config automatic_scheme			longest_side
bspc config initial_polarity			second_child
bspc config removal_adjustment			true
bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_follows_monitor		true
bspc config pointer_motion_interval		7

### AutoStart ###
sxhkd &
picom &
nitrogen --restore &
xfce4-power-manager &

if xrandr | grep "DP-4 connected"; then
    xrandr --output DP-4 --mode 1920x1080 --rate 165 --primary
fi

if xrandr | grep "eDP-1 connected"; then
    xrandr --output eDP-1 --mode 1366x768 --primary
fi
