#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#8B34DE"
bspc config presel_feedback_color "#6272a4"




xsetroot -cursor_name volantes_cursors &

xrandr --auto --output HDMI-1 --mode 1360x768
nitrogen  --restore &
